use_frameworks!

target 'MyTestLib_Example' do
  pod 'MyTestLib', :path => '../'

  target 'MyTestLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
